### ISSUE TITLE
Ошибка кодирования json ответа

### ISSUE THREAD

**Issue by maestroprog** [maestroprog/esockets#11]
Делаем запрос по адресу [https://panel.netangels.ru/api/cvds/v1/os-images/?page=3](https://panel.netangels.ru/api/cvds/v1/os-images/?page=3)

получаем ответ:

```json

{
  "count": 29,
  "next": null,
  "previous": "https://panel.netangels.ru/api/cvds/v1/os-images/?page=2",
  "results": [
    .....
    {
      "id": 39,
      "description": "GitLab (Debian Jessie)",
      "arch": [
        64
      ],
      "required_data": "[u'domain']"
    },
    .....
  ]
}
```

а должно быть так:

```json
{
  "count": 29,
  "next": null,
  "previous": "https://panel.netangels.ru/api/cvds/v1/os-images/?page=2",
  "results": [
    .....
    {
      "id": 39,
      "description": "GitLab (Debian Jessie)",
      "arch": [
        64
      ],
      "required_data": ["domain"]
    },
    .....
  ]
}
```

Проблема в том, что массив в поле `required_data` почему-то некорректно кодируется в виде json строки и со вставками символов `u` (похоже, это какое-то экранирование апострофов)

Для корректного декодирования этого поля пришлось подставить костыль:
```php
$data = json_decode(str_replace(['u\'', '\''], ['"', '"'], $img['required_data']), true);
```

**Comment by CrazyDuckDuck** [comment]
Добрый вечер, мы исправили баг. Костыль можно убрать :)

**Comment by maestroprog** [comment]
@SleepWalk2 благодарю :)
а у меня другой баг - issue не [там где нужно](https://github.com/maestroprog/netangels-cvds-api) создал)
